platform: linux
inputs:
  - name: source
image_resource:
  type: docker-image
  source:
    username: ((internal_maven_username))
    password: ((internal_maven_password))
    repository: "docker:443/ci/gradle"
    insecure_registries: ["paradiso.nexus:8083"]
params:
  INTERNAL_MAVEN_USERNAME: ((internal_maven_username))
  INTERNAL_MAVEN_PASSWORD: ((internal_maven_password))
  BUTLER_API_KEY: ((itch_api_key))
caches:
  - path: gradle/wrapper
  - path: gradle/caches
run:
  path: source/.ci/build.sh
outputs:
  - name: github-release
