resources:
  - name: source
    type: git
    source:
      uri: "https://github.com/sirnuke/outrogue.git"
      tag_filter: "v*"
      username: ((github_username))
      password: ((github_access_token))
    check_every: "30m"
  - name: gh-release
    type: github-release
    source:
      owner: ((github_username))
      repository: outrogue
      access_token: ((github_access_token))

jobs:
  - name: gradle
    plan:
      - get: source
        trigger: true
      - task: execute-gradle
        file: source/.ci/build.yml
        params:
          BUILD_TYPE: release
        vars:
          nexus_username: ((nexus_username))
          nexus_password: ((nexus_password))
          itch_api_key: ((itch_api_key))
        outputs:
          - name: github-release
      - put: gh-release
        inputs:
          - name: github-release
        params:
          name: github-release/github-version
          tag: github-release/github-version
          tag_prefix: v
          globs:
            - "github-release/*.jar"
