resources:
  - name: source
    type: git
    source:
      uri: "https://github.com/sirnuke/outrogue.git"
      username: ((github_username))
      password: ((github_access_token))
    check_every: "30m"

jobs:
  - name: gradle
    plan:
      - get: source
        trigger: true
      - task: execute-gradle
        file: source/.ci/build.yml
        params:
          BUILD_TYPE: snapshot
        vars:
          internal_maven_username: ((internal_maven_username))
          internal_maven_password: ((internal_maven_password))
          itch_api_key: ((itch_api_key))
