// Rules related to performing the sleeping behavior, if nothing else is available

package com.degrendel.outrogue.agent.rules

import com.degrendel.outrogue.common.world.creatures.Creature
import com.degrendel.outrogue.common.agent.Sleep
import com.degrendel.outrogue.agent.goals.*
import com.degrendel.outrogue.agent.goals.actions.*
import com.degrendel.outrogue.agent.RogueAgent
import org.slf4j.Logger

global Logger L
global RogueAgent agent
global Creature creature

dialect "mvel"

rule "Create sleep goal"
salience 50
when
    DecideAction()
then
    L.debug("Inserting sleep goal")
    insertLogical(new SleepGoal())
end

rule "Create sleep action and mark goal as evaluated"
when
    $goal : SleepGoal(action == null)
then
    L.debug("Creating sleep action, marking goal as evaluated")
    modify($goal) { action = new Sleep(creature), evaluated = true, applicable = true }
end